/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus.hw01.gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class HelloOtusTest {
    @Test public void testAppHasAGreeting() {
        HelloOtus classUnderTest = new HelloOtus();
        String expect = "Hello Otus 2020.";
        assertEquals(expect, classUnderTest.getGreeting());
    }
}
