/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw05;

import jdk.jfr.FlightRecorder;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        Flying airplan = new Airplain();
        airplan.startFlight(Arrays.asList("Spb", "Moscow", "Bali", "Java"));
        airplan.endFlight("success");
        airplan.canBeNonLoggable("absent");

        Flying an2 = AOPLoggingBuilder.build(airplan, Flying.class);

        an2.startFlight(Arrays.asList("Spb", "Moscow", "Bali", "Java"));
        an2.endFlight("Ok");
        an2.canBeNonLoggable("Void");



    }
}
