/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw08.mygson;

import org.junit.Test;
import static org.junit.Assert.*;

import com.google.gson.Gson;


public class MyGsonTest {
    @Test public void testNull() {
        assertEquals("{}", MyGson.toJson(null));
    }

    @Test public void testObjectSimple(){
        assertEquals("{}", MyGson.toJson(new Object()));
    }

    @Test public void testMyObject(){
//        assertEquals("{}", MyGson.toJson(new MyObject()));
        Gson g = new Gson();
        System.out.println(g.toJson(new MyObject()));
    }

    @Test public void testString(){
        assertEquals("{}", "hello");
    }

    @Test public void testInteger(){
        assertEquals("{}", new Integer(4));
    }
}
