/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw08.mygson;

import org.junit.Test;
import static org.junit.Assert.*;

import com.google.gson.Gson;


public class MyGsonTest {
    @Test public void testNull() {
        assertEquals("{}", MyGson.toJson(null));
    }

    @Test public void testObjectSimple(){
        assertEquals("{}", MyGson.toJson(new Object()));
    }

    @Test public void testMyObject(){
        String asJson = MyGson.toJson(new MyObject());
        System.out.println(asJson);
        Gson g = new Gson();
        System.out.println(g.toJson(new MyObject()));
        MyObject backed = g.fromJson(asJson, MyObject.class);

    }

    @Test public void testString(){
//        assertEquals("{}", MyGson.toJson("hello"));
        Gson g = new Gson();
        System.out.println(g.toJson("Hello"));
    }

    @Test public void testInteger(){
        assertEquals("{}", MyGson.toJson(null));
    }
}