/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus.hw01.gradle;

import com.google.common.collect.Lists;
import java.util.List;

public class HelloOtus {
    public String getGreeting() {
        return "Hello Otus 2020.";
    }

    public static void main(String[] args) {
        String greetings = new HelloOtus().getGreeting();
        List l = Lists.charactersOf(greetings);
        System.out.println(l);
    }
}
