/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw15;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class.getName());

    public static void main(String[] args) throws InterruptedException {

        logger.info("Start");

        NumberPrint task = new NumberPrint(6, 21);

        Thread first = new Thread(() -> task.print(1));
        Thread second = new Thread(() -> task.print(2));

        first.start();
        second.start();

        first.join();
        second.join();
        logger.info("End");
    }
}

